services:
  # SexShop API
  - type: web
    name: sexshop-api
    env: docker
    rootDir: .        # <--- CAMBIADO: El punto (.) significa la raíz
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: ohio
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: UseSqlite
        value: "true"
      - key: ConnectionStrings__SqliteConnection
        value: Data Source=SexShop.db
      - key: AllowedOrigins
        value: "http://localhost:5185,https://localhost:7137,https://sexshop-web.onrender.com"

  # SexShop Web
  - type: web
    name: sexshop-web
    env: docker
    rootDir: .        # <--- CAMBIADO: El punto (.) significa la raíz
    dockerfilePath: Dockerfile.web
    dockerContext: .
    plan: free
    region: ohio
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ApiSettings__BaseUrl
        fromService:
          type: web
          name: sexshop-api
          property: host